### ISSUE TITLE
I2C Transfer Error

### ISSUE THREAD

**Issue by flavius-t** [EdgePi-Cloud/edgepi-python-sdk#221]
I am using the SDK version `1.1.15` for our data collector (this should be identical to our current dev), and I occasionally get this error. I run the data collector, start up an ADC read, and everything works fine. Then I shutdown the data collector, and when I try to start it again immediately, this error pops up. It seems to go away if I try restarting after waiting a few minutes.

```
Traceback (most recent call last):
  File "/home/flavius/repos/edgepi-data-collector/venv_test/lib/python3.9/site-packages/periphery/i2c.py", line 135, in transfer
    fcntl.ioctl(self._fd, I2C._I2C_IOC_RDWR, i2c_xfer, False)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/flavius/repos/edgepi-data-collector/edgepi_data_collector.py", line 61, in <module>
    collector = DataCollectorADC(read_interval, state)
  File "/home/flavius/repos/edgepi-data-collector/collectors/data_collector_adc.py", line 48, in __init__
    self.adc = EdgePiADC()
  File "/home/flavius/repos/edgepi-data-collector/venv_test/lib/python3.9/site-packages/edgepi/adc/edgepi_adc.py", line 225, in __init__
    eeprom_data  = eeprom.get_edgepi_reserved_data()
  File "/home/flavius/repos/edgepi-data-collector/venv_test/lib/python3.9/site-packages/edgepi/calibration/edgepi_eeprom.py", line 100, in get_edgepi_reserved_data
    self.eeprom_layout.ParseFromString(self.__read_edgepi_reserved_memory())
  File "/home/flavius/repos/edgepi-data-collector/venv_test/lib/python3.9/site-packages/edgepi/calibration/edgepi_eeprom.py", line 74, in __read_edgepi_reserved_memory
    buff_list = self.sequential_read(EdgePiMemoryInfo.BUFF_START.value, mem_size)
  File "/home/flavius/repos/edgepi-data-collector/venv_test/lib/python3.9/site-packages/edgepi/calibration/edgepi_eeprom.py", line 128, in sequential_read
    read_result = self.transfer(EEPROMInfo.DEV_ADDR.value, msg)
  File "/home/flavius/repos/edgepi-data-collector/venv_test/lib/python3.9/site-packages/edgepi/peripherals/i2c.py", line 57, in transfer
    self.i2cdev.transfer(dev_addr, msg)
  File "/home/flavius/repos/edgepi-data-collector/venv_test/lib/python3.9/site-packages/periphery/i2c.py", line 137, in transfer
    raise I2CError(e.errno, "I2C transfer: " + e.strerror)
periphery.i2c.I2CError: [Errno 110] I2C transfer: Connection timed out
```

**Comment by flavius-t** [comment]
The error also seems to go away if I start up an LED collector read, and then try restarting the ADC collector.
