### ISSUE TITLE
DAC voltage write upper limit

### ISSUE THREAD

**Issue by iaj2** [EdgePi-Cloud/edgepi-python-sdk#306]
Should allow voltages 0<=5 when gain is false and 0<=10 when gain is true but instead does 0<5 and 0<10.
```

from edgepi.dac.dac_constants import DACChannel as Ch
from edgepi.dac.edgepi_dac import EdgePiDAC

# initialize DAC
edgepi_dac = EdgePiDAC()

# setting DAC range 0-10V
edgepi_dac.set_dac_gain(True)

# write voltage value of 10 V to analog out pin number 4
edgepi_dac.write_voltage(Ch.AOUT4, 10)

# read state of DAC output 1
code, voltage, gain = edgepi_dac.get_state(Ch.AOUT4, True, True, True)

print(code,voltage,gain)
```

Traceback (most recent call last):
  File "/home/tf1/projects/AutoFanProject/test_dac_fan.py", line 11, in <module>
    edgepi_dac.write_voltage(Ch.AOUT4, 10)
  File "/home/tf1/venv/lib/python3.9/site-packages/edgepi/dac/edgepi_dac.py", line 126, in write_voltage
    self.transfer(self.dac_ops.generate_write_and_update_command(analog_out.value, code))
  File "/home/tf1/venv/lib/python3.9/site-packages/edgepi/dac/dac_commands.py", line 27, in generate_write_and_update_command
    self.check_range(data, 0, CALIB_CONSTS.RANGE.value-1)
  File "/home/tf1/venv/lib/python3.9/site-packages/edgepi/dac/dac_commands.py", line 145, in check_range
    raise ValueError(f"Target {target} is out of range ")
ValueError: Target 65536 is out of range

**Comment by farzadpanahi** [comment]
@iaj2 please put the traceback in code format (using 3 x backquotes) to make it easier to read : )
